// This file was generated by Prisma, and assumes you have installed:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
  },

  datasource: {
    // Used by Prisma CLI for migrations/introspection.
    // This should NOT be the transaction pooler.
    url: process.env["DIRECT_URL"],
  },
});